# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Flix' do
  pod 'RxSwift', '6.5.0'
  pod 'RxAlamofire', '6.1.1'
end

target 'FlixLocal' do
  pod 'RxSwift', '6.5.0'
  pod 'RxAlamofire', '6.1.1'
end

target 'FlixUnitTests' do
  pod 'RxAlamofire', '6.1.1'
  pod 'RxSwift', '6.5.0'
end

target 'FlixSnapshotTests' do
  pod 'RxAlamofire', '6.1.1'
  pod 'RxSwift', '6.5.0'
  pod 'SnapshotTesting', '1.9.0'
end
